import { describe, it, expect } from "vitest";
import { parseAcfOptions, generateAcfOptionsModule } from "../src/acf-options-extractor.js";

describe("parseAcfOptions", () => {
  it("extracts string fields", () => {
    const fields = parseAcfOptions({ site_name: "My Site", tagline: "A blog" });
    expect(fields).toHaveLength(2);
    expect(fields[0]).toEqual({ name: "site_name", value: "My Site", type: "string" });
    expect(fields[1]).toEqual({ name: "tagline", value: "A blog", type: "string" });
  });

  it("extracts number fields", () => {
    const fields = parseAcfOptions({ max_posts: 10 });
    expect(fields[0]).toEqual({ name: "max_posts", value: 10, type: "number" });
  });

  it("extracts boolean fields", () => {
    const fields = parseAcfOptions({ show_sidebar: true, dark_mode: false });
    expect(fields[0]).toEqual({ name: "show_sidebar", value: true, type: "boolean" });
    expect(fields[1]).toEqual({ name: "dark_mode", value: false, type: "boolean" });
  });

  it("detects image type from object with url and alt", () => {
    const fields = parseAcfOptions({
      logo: { url: "https://example.com/logo.png", alt: "Logo", width: 200, height: 100 },
    });
    expect(fields[0]!.type).toBe("image");
  });

  it("detects image type from object with url and width (no alt)", () => {
    const fields = parseAcfOptions({
      banner: { url: "https://example.com/banner.jpg", width: 1200 },
    });
    expect(fields[0]!.type).toBe("image");
  });

  it("detects array type", () => {
    const fields = parseAcfOptions({ social_links: ["https://twitter.com", "https://github.com"] });
    expect(fields[0]!.type).toBe("array");
  });

  it("detects plain object type (not image)", () => {
    const fields = parseAcfOptions({ settings: { color: "blue", font: "Arial" } });
    expect(fields[0]!.type).toBe("object");
  });

  it("treats null values as string type", () => {
    const fields = parseAcfOptions({ empty_field: null });
    expect(fields[0]).toEqual({ name: "empty_field", value: null, type: "string" });
  });

  it("handles nested acf key in response", () => {
    const fields = parseAcfOptions({
      acf: { site_name: "Nested Site", count: 42 },
    });
    expect(fields).toHaveLength(2);
    expect(fields[0]!.name).toBe("site_name");
    expect(fields[1]!.name).toBe("count");
  });

  it("returns empty array for empty input", () => {
    const fields = parseAcfOptions({});
    expect(fields).toHaveLength(0);
  });
});

describe("generateAcfOptionsModule", () => {
  it("produces valid TypeScript interface", () => {
    const result = generateAcfOptionsModule({ site_name: "Test", count: 5 });
    expect(result.generatedCode).toContain("export interface SiteOptions {");
    expect(result.generatedCode).toContain("site_name: string;");
    expect(result.generatedCode).toContain("count: number;");
    expect(result.generatedCode).toContain("}");
  });

  it("produces siteOptions constant with correct values", () => {
    const result = generateAcfOptionsModule({ enabled: true, title: "Hello" });
    expect(result.generatedCode).toContain("export const siteOptions: SiteOptions = {");
    expect(result.generatedCode).toContain('title: "Hello",');
    expect(result.generatedCode).toContain("enabled: true,");
  });

  it("generates image type annotation", () => {
    const result = generateAcfOptionsModule({
      logo: { url: "https://example.com/logo.png", alt: "Logo" },
    });
    expect(result.generatedCode).toContain(
      "logo: { url: string; alt: string; width?: number; height?: number };",
    );
  });

  it("generates array and object type annotations", () => {
    const result = generateAcfOptionsModule({
      items: [1, 2, 3],
      config: { key: "value" },
    });
    expect(result.generatedCode).toContain("items: unknown[];");
    expect(result.generatedCode).toContain("config: Record<string, unknown>;");
  });

  it("returns fields alongside generated code", () => {
    const result = generateAcfOptionsModule({ name: "Site" });
    expect(result.fields).toHaveLength(1);
    expect(result.fields[0]!.name).toBe("name");
    expect(result.generatedCode).toBeTruthy();
  });

  it("produces empty interface for empty input", () => {
    const result = generateAcfOptionsModule({});
    expect(result.fields).toHaveLength(0);
    expect(result.generatedCode).toContain("export interface SiteOptions {");
    expect(result.generatedCode).toContain("}");
    // Interface body should be empty (no fields between braces)
    const interfaceMatch = result.generatedCode.match(/export interface SiteOptions \{\n\}/);
    expect(interfaceMatch).toBeTruthy();
  });

  it("includes header comment", () => {
    const result = generateAcfOptionsModule({ x: 1 });
    expect(result.generatedCode).toContain("Generated by wp-transfer");
  });
});
