/**
 * ACF Options Page Extractor
 *
 * Extracts ACF Options Page data via WordPress REST API
 * and generates type-safe site options module.
 */

// ── Types ──

export interface AcfOptionsField {
  name: string;
  value: unknown;
  type: "string" | "number" | "boolean" | "image" | "array" | "object";
}

export interface AcfOptionsResult {
  fields: AcfOptionsField[];
  generatedCode: string;
}

// ── Type inference ──

function inferFieldType(value: unknown): AcfOptionsField["type"] {
  if (value === null || value === undefined) return "string";
  if (typeof value === "boolean") return "boolean";
  if (typeof value === "number") return "number";
  if (Array.isArray(value)) return "array";
  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    if (obj.url && (obj.alt !== undefined || obj.width !== undefined)) return "image";
    return "object";
  }
  return "string";
}

// ── Code generation ──

function generateTypeForField(field: AcfOptionsField): string {
  switch (field.type) {
    case "string": return "string";
    case "number": return "number";
    case "boolean": return "boolean";
    case "image": return "{ url: string; alt: string; width?: number; height?: number }";
    case "array": return "unknown[]";
    case "object": return "Record<string, unknown>";
  }
}

function generateOptionsModule(fields: AcfOptionsField[]): string {
  const lines: string[] = [];
  lines.push("/**");
  lines.push(" * Site Options — extracted from ACF Options Page");
  lines.push(" * Generated by wp-transfer");
  lines.push(" */");
  lines.push("");

  // Type definition
  lines.push("export interface SiteOptions {");
  for (const field of fields) {
    lines.push(`  ${field.name}: ${generateTypeForField(field)};`);
  }
  lines.push("}");
  lines.push("");

  // Default values
  lines.push("export const siteOptions: SiteOptions = {");
  for (const field of fields) {
    lines.push(`  ${field.name}: ${JSON.stringify(field.value)},`);
  }
  lines.push("};");

  return lines.join("\n");
}

// ── Public API ──

/**
 * Parse ACF Options API response into typed fields.
 */
export function parseAcfOptions(apiResponse: Record<string, unknown>): AcfOptionsField[] {
  const acf = (apiResponse.acf ?? apiResponse) as Record<string, unknown>;
  const fields: AcfOptionsField[] = [];

  for (const [name, value] of Object.entries(acf)) {
    fields.push({
      name,
      value,
      type: inferFieldType(value),
    });
  }

  return fields;
}

/**
 * Generate a type-safe site options module from ACF Options data.
 */
export function generateAcfOptionsModule(apiResponse: Record<string, unknown>): AcfOptionsResult {
  const fields = parseAcfOptions(apiResponse);
  const generatedCode = generateOptionsModule(fields);
  return { fields, generatedCode };
}
