/**
 * Admin Page Scaffold Generator
 *
 * Generates React admin pages (Next.js App Router) from PHP template analysis.
 * Maps PHP admin templates to Next.js pages with Prisma ORM integration.
 */
import type { PhpFileAnalysis, InputParam } from "./php-analyzer.js";
import type { TableDefinition } from "./schema-to-prisma.js";
import {
  fieldTypeToInputType,
  pluralizeResource,
  toCamelCase,
  toPascalCase,
} from "./generator-utils.js";

// ── Types ──

export type UiFramework = "plain" | "tailwind";

export interface AdminScaffoldOptions {
  uiFramework?: UiFramework;
  /** Add a server-side active-session guard to the shared admin layout. */
  requireAuth?: boolean;
}

export interface AdminPage {
  path: string;
  content: string;
  type: "list" | "form" | "detail" | "dashboard";
}

// ── Route mapping from PHP templates ──

interface RouteRule {
  pattern: RegExp;
  routeBuilder: (match: RegExpMatchArray) => string;
  type: AdminPage["type"];
}

const ROUTE_RULES: RouteRule[] = [
  // page-*-search-list.php → search page (list+form)
  {
    pattern: /^page-(\w+)-search-list\.php$/,
    routeBuilder: (m) => `app/(admin)/${pluralize(m[1]!)}/search/page.tsx`,
    type: "list",
  },
  // page-*-summary.php → summary/detail page
  {
    pattern: /^page-(\w+)-summary\.php$/,
    routeBuilder: (m) => `app/(admin)/${pluralize(m[1]!)}/summary/page.tsx`,
    type: "detail",
  },
  // page-*-slot.php → slots sub-page
  {
    pattern: /^page-(\w+)-slot\.php$/,
    routeBuilder: (m) => `app/(admin)/${pluralize(m[1]!)}/[id]/slots/page.tsx`,
    type: "list",
  },
  // page-*-copy.php → copy page
  {
    pattern: /^page-(\w+)-copy\.php$/,
    routeBuilder: (m) => `app/(admin)/${pluralize(m[1]!)}/[id]/copy/page.tsx`,
    type: "form",
  },
  // page-*-update.php → edit page
  {
    pattern: /^page-(\w+)-update\.php$/,
    routeBuilder: (m) => `app/(admin)/${pluralize(m[1]!)}/[id]/page.tsx`,
    type: "form",
  },
  // page-*-list.php → list page
  {
    pattern: /^page-(\w+)-list\.php$/,
    routeBuilder: (m) => `app/(admin)/${pluralize(m[1]!)}/page.tsx`,
    type: "list",
  },
  // page-new-*.php → new creation page
  {
    pattern: /^page-new-(\w+)\.php$/,
    routeBuilder: (m) => `app/(admin)/${pluralize(m[1]!)}/new/page.tsx`,
    type: "form",
  },
  // page-*.php → new creation page (generic)
  {
    pattern: /^page-(\w+)\.php$/,
    routeBuilder: (m) => `app/(admin)/${pluralize(m[1]!)}/new/page.tsx`,
    type: "form",
  },
];

// ── Helpers ──

export function pluralize(word: string): string {
  return pluralizeResource(word);
}

function findTableForResource(
  resourceName: string,
  tables: TableDefinition[],
): TableDefinition | undefined {
  // Try exact match
  const exact = tables.find((t) => t.name === resourceName);
  if (exact) return exact;

  // Try singular form
  const singular = resourceName.replace(/s$/, "");
  const singularMatch = tables.find((t) => t.name === singular);
  if (singularMatch) return singularMatch;

  // Try with underscores
  const underscored = resourceName.replace(/-/g, "_");
  return tables.find((t) => t.name === underscored);
}

function mapPhpToRoute(
  fileName: string,
): { path: string; type: AdminPage["type"]; resource: string } | null {
  for (const rule of ROUTE_RULES) {
    const match = fileName.match(rule.pattern);
    if (match) {
      return {
        path: rule.routeBuilder(match),
        type: rule.type,
        resource: match[1]!,
      };
    }
  }
  return null;
}

function fieldLabel(name: string): string {
  // Convert snake_case to readable Japanese-friendly label
  return name.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function codeKey(name: string): string {
  return JSON.stringify(name);
}

function recordAccess(record: string, key: string): string {
  return `${record}[${codeKey(key)}]`;
}

function recordUpdate(key: string, value: string): string {
  return `[${codeKey(key)}]: ${value}`;
}

function jsxText(value: string): string {
  return `{${JSON.stringify(value)}}`;
}

// ── CSS generator ──

export function generateGlobalsCss(): string {
  return `/* WP Admin Faithful CSS — generated by wp-transfer */
:root {
  --wp-admin-dark: #23282d;
  --wp-admin-darker: #1d2125;
  --wp-primary: #0073aa;
  --wp-primary-hover: #006799;
  --wp-success: #46b450;
  --wp-warning: #ffb900;
  --wp-error: #dc3232;
  --wp-text: #23282d;
  --wp-text-light: #666;
  --wp-border: #ccd0d4;
  --wp-bg: #f0f0f1;
  --wp-white: #fff;
}

*, *::before, *::after {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
  font-size: 14px;
  color: var(--wp-text);
}

/* ── Layout ── */

.wp-admin-sidebar {
  width: 240px;
  background-color: var(--wp-admin-dark);
  color: #fff;
  padding: 24px 0;
  flex-shrink: 0;
  min-height: 100vh;
}

.wp-admin-sidebar h2 {
  padding: 0 16px;
  margin: 0 0 32px;
  font-size: 18px;
  font-weight: bold;
}

.wp-admin-menu-item {
  display: block;
  padding: 10px 16px;
  color: #d1d5db;
  text-decoration: none;
  font-size: 14px;
}

.wp-admin-menu-item:hover {
  background-color: var(--wp-primary);
  color: #fff;
}

.wp-admin-menu-item.active {
  background-color: var(--wp-primary);
  color: #fff;
}

.wp-admin-content {
  flex: 1;
  background-color: var(--wp-bg);
  overflow: auto;
}

/* ── Common ── */

.wp-admin-wrap {
  padding: 20px;
}

.wp-admin-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.wp-admin-title {
  font-size: 23px;
  font-weight: 400;
  margin: 0 0 16px;
  padding: 9px 0 4px;
  line-height: 1.3;
  color: var(--wp-text);
}

.wp-admin-title-action {
  display: inline-block;
  padding: 4px 8px;
  margin-left: 4px;
  font-size: 13px;
  line-height: 1.5;
  text-decoration: none;
  border: 1px solid var(--wp-border);
  border-radius: 3px;
  color: var(--wp-primary);
  background: transparent;
  cursor: pointer;
}

.wp-admin-title-action:hover {
  border-color: var(--wp-primary);
  color: var(--wp-primary-hover);
}

/* ── Notices ── */

.wp-notice {
  padding: 12px 16px;
  margin: 8px 0 16px;
  border-left: 4px solid var(--wp-primary);
  background: var(--wp-white);
  box-shadow: 0 1px 1px rgba(0,0,0,.04);
}

.wp-notice p {
  margin: 0;
}

.wp-notice-success {
  border-left-color: var(--wp-success);
}

.wp-notice-warning {
  border-left-color: var(--wp-warning);
}

.wp-notice-error {
  border-left-color: var(--wp-error);
}

/* ── List Table ── */

.wp-list-table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  background: var(--wp-white);
}

.wp-list-table thead th {
  padding: 8px 10px;
  text-align: left;
  font-size: 14px;
  font-weight: 400;
  color: var(--wp-text);
  border-bottom: 1px solid var(--wp-border);
}

.wp-list-table tbody td {
  padding: 8px 10px;
  font-size: 13px;
  vertical-align: top;
  border-bottom: 1px solid #e1e1e1;
}

.wp-list-table tbody tr:hover {
  background-color: #f5f5f5;
}

.wp-list-table tbody tr:nth-child(even) {
  background-color: #f9f9f9;
}

.wp-list-table tbody tr:nth-child(even):hover {
  background-color: #f5f5f5;
}

.wp-list-table a {
  color: var(--wp-primary);
  text-decoration: none;
}

.wp-list-table a:hover {
  color: var(--wp-primary-hover);
  text-decoration: underline;
}

/* ── Table Nav ── */

.wp-table-nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 4px 0;
  margin-bottom: 8px;
}

.wp-table-nav .displaying-num {
  font-size: 13px;
  color: var(--wp-text-light);
  font-style: italic;
}

/* ── Buttons ── */

.wp-button {
  display: inline-block;
  padding: 6px 12px;
  font-size: 13px;
  line-height: 1.5;
  color: var(--wp-primary);
  background: #f3f5f6;
  border: 1px solid var(--wp-border);
  border-radius: 3px;
  cursor: pointer;
  text-decoration: none;
  white-space: nowrap;
  vertical-align: middle;
}

.wp-button:hover {
  background: #f1f1f1;
  border-color: #999;
  color: var(--wp-primary-hover);
}

.wp-button-primary {
  background: var(--wp-primary);
  border-color: var(--wp-primary);
  color: var(--wp-white);
}

.wp-button-primary:hover {
  background: var(--wp-primary-hover);
  border-color: var(--wp-primary-hover);
  color: var(--wp-white);
}

.wp-button-primary:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.wp-button-danger {
  background: var(--wp-error);
  border-color: var(--wp-error);
  color: var(--wp-white);
}

.wp-button-danger:hover {
  background: #be2c2c;
  border-color: #be2c2c;
  color: var(--wp-white);
}

.wp-button-add {
  background: var(--wp-success);
  border-color: var(--wp-success);
  color: var(--wp-white);
}

.wp-button-add:hover {
  background: #3da740;
  border-color: #3da740;
  color: var(--wp-white);
}

/* ── Forms ── */

.wp-form-field {
  margin-bottom: 16px;
}

.wp-form-field label {
  display: block;
  margin-bottom: 4px;
  font-weight: 600;
  font-size: 14px;
}

.wp-form-input {
  width: 100%;
  padding: 6px 8px;
  font-size: 14px;
  border: 1px solid var(--wp-border);
  border-radius: 4px;
  background: var(--wp-white);
  color: var(--wp-text);
  line-height: 2;
}

.wp-form-input:focus {
  border-color: var(--wp-primary);
  box-shadow: 0 0 0 1px var(--wp-primary);
  outline: none;
}

.wp-form-select {
  width: 100%;
  padding: 6px 8px;
  font-size: 14px;
  border: 1px solid var(--wp-border);
  border-radius: 4px;
  background: var(--wp-white);
  color: var(--wp-text);
  line-height: 2;
}

.wp-form-select:focus {
  border-color: var(--wp-primary);
  box-shadow: 0 0 0 1px var(--wp-primary);
  outline: none;
}

.wp-form-textarea {
  width: 100%;
  padding: 6px 8px;
  font-size: 14px;
  border: 1px solid var(--wp-border);
  border-radius: 4px;
  background: var(--wp-white);
  color: var(--wp-text);
  resize: vertical;
}

.wp-form-textarea:focus {
  border-color: var(--wp-primary);
  box-shadow: 0 0 0 1px var(--wp-primary);
  outline: none;
}

.wp-form-error {
  color: var(--wp-error);
  font-size: 13px;
  margin-top: 4px;
}

/* ── Spinner ── */

.wp-spinner {
  display: inline-block;
  width: 16px;
  height: 16px;
  border: 2px solid rgba(255,255,255,0.3);
  border-top-color: #fff;
  border-radius: 50%;
  animation: wp-spin 0.6s linear infinite;
  vertical-align: middle;
  margin-left: 8px;
}

@keyframes wp-spin {
  to { transform: rotate(360deg); }
}

/* ── Dashboard ── */

.wp-dashboard-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 16px;
}

.wp-dashboard-card {
  background: var(--wp-white);
  border: 1px solid var(--wp-border);
  border-radius: 0;
  text-decoration: none;
  color: inherit;
  display: block;
}

.wp-dashboard-card:hover {
  border-color: #999;
}

.wp-dashboard-card-header {
  padding: 8px 12px;
  border-bottom: 1px solid var(--wp-border);
  font-size: 14px;
  font-weight: 600;
}

.wp-dashboard-card-body {
  padding: 16px 12px;
}

.wp-dashboard-card-count {
  font-size: 32px;
  font-weight: 400;
  color: var(--wp-primary);
}

/* ── Slot / Array Fields ── */

.wp-slot-section {
  margin-top: 24px;
  border-top: 1px solid var(--wp-border);
  padding-top: 16px;
}

.wp-slot-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.wp-slot-header h3 {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
}

.wp-slot-row {
  display: flex;
  gap: 8px;
  margin-bottom: 8px;
  align-items: center;
}

.wp-slot-row input {
  flex: 1;
  padding: 6px 8px;
  font-size: 14px;
  border: 1px solid var(--wp-border);
  border-radius: 4px;
}

/* ── Empty State ── */

.wp-empty-state {
  text-align: center;
  padding: 48px 20px;
  color: var(--wp-text-light);
  font-size: 14px;
}
`;
}

// ── Page generators ──

function generateListPage(
  resource: string,
  table: TableDefinition | undefined,
  analyses: PhpFileAnalysis[],
  fw: UiFramework,
): string {
  const modelName = toPascalCase(table?.name ?? resource);
  const camelModel = toCamelCase(table?.name ?? resource);
  const columns = table?.columns ?? [];
  const displayColumns = columns.slice(0, 8); // Show first 8 columns

  if (fw === "tailwind") {
    return `import { prisma } from "@/lib/db";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default async function ${modelName}ListPage() {
  const items = await prisma.${camelModel}.findMany({
    orderBy: { id: "desc" },
    take: 100,
  });

  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">${modelName} 一覧</h1>
        <Link
          href="/${pluralize(resource)}/new"
          className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
        >
          新規作成
        </Link>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="bg-gray-100">
${displayColumns.map((c) => `              <th className="px-4 py-3 text-left border-b-2 border-gray-200 text-sm">${jsxText(c.comment ?? fieldLabel(c.name))}</th>`).join("\n")}
              <th className="px-4 py-3 text-left border-b-2 border-gray-200 text-sm">操作</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.id} className="border-b border-gray-200">
${displayColumns.map((c) => `                <td className="px-4 py-3 text-sm">{String(${recordAccess("item", c.name)} ?? "")}</td>`).join("\n")}
                <td className="px-4 py-3">
                  <Link
                    href={\`/${pluralize(resource)}/\${item.id}\`}
                    className="text-blue-600 underline mr-2"
                  >
                    詳細
                  </Link>
                  <Link
                    href={\`/${pluralize(resource)}/\${item.id}/edit\`}
                    className="text-blue-600 underline"
                  >
                    編集
                  </Link>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {items.length === 0 && (
        <p className="text-center py-12 text-gray-500">
          データがありません
        </p>
      )}
    </div>
  );
}
`;
  }

  return `import { prisma } from "@/lib/db";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default async function ${modelName}ListPage() {
  const items = await prisma.${camelModel}.findMany({
    orderBy: { id: "desc" },
    take: 100,
  });

  return (
    <div className="wp-admin-wrap">
      <div className="wp-admin-header">
        <h1 className="wp-admin-title">${modelName} 一覧</h1>
        <Link href="/${pluralize(resource)}/new" className="wp-admin-title-action">
          新規追加
        </Link>
      </div>

      <div className="wp-table-nav">
        <span className="displaying-num">{items.length} 件</span>
      </div>

      <table className="wp-list-table">
        <thead>
          <tr>
${displayColumns.map((c) => `            <th>${jsxText(c.comment ?? fieldLabel(c.name))}</th>`).join("\n")}
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item) => (
            <tr key={item.id}>
${displayColumns.map((c) => `              <td>{String(${recordAccess("item", c.name)} ?? "")}</td>`).join("\n")}
              <td>
                <Link href={\`/${pluralize(resource)}/\${item.id}\`} className="wp-row-action">
                  詳細
                </Link>
                {" / "}
                <Link href={\`/${pluralize(resource)}/\${item.id}/edit\`} className="wp-row-action">
                  編集
                </Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {items.length === 0 && (
        <p className="wp-empty-state">
          データがありません
        </p>
      )}
    </div>
  );
}
`;
}

function generateFormFieldJsx(f: import("./php-analyzer.js").FormField, index: number): string {
  if (f.type === "hidden") return "";

  if (f.type === "select" && f.options) {
    const opts = f.options
      .map((o) => `              <option value="${o.value}">${o.label}</option>`)
      .join("\n");
    return `        <div className="wp-form-field">
          <label>
            ${f.label}
          </label>
          <select
            className="wp-form-select"
            value={String(${recordAccess("form", f.name)} ?? "")}
            onChange={(e) => setForm({ ...form, ${recordUpdate(f.name, "e.target.value")} })}
          >
            <option value="">選択してください</option>
${opts}
          </select>
        </div>`;
  }

  if (f.type === "textarea") {
    return `        <div className="wp-form-field">
          <label>
            ${f.label}
          </label>
          <textarea
            className="wp-form-textarea"
            rows={5}
            value={String(${recordAccess("form", f.name)} ?? "")}
            onChange={(e) => setForm({ ...form, ${recordUpdate(f.name, "e.target.value")} })}
          />
        </div>`;
  }

  if (f.type === "file") {
    return `        <div className="wp-form-field">
          <label>
            ${f.label}
          </label>
          <input
            type="file"${f.accept ? `\n            accept="${f.accept}"` : ""}
            onChange={(e) => setFile(e.target.files?.[0] ?? null)}
          />
        </div>`;
  }

  const inputType = f.type === "datetime-local" || f.type === "date" || f.type === "url"
    ? f.type
    : f.type === "number" ? "number" : "text";

  const valueCoerce = f.type === "number"
    ? "Number(e.target.value)"
    : "e.target.value";

  return `        <div className="wp-form-field">
          <label>
            ${f.label}
          </label>
          <input
            className="wp-form-input"
            type="${inputType}"
            value={String(${recordAccess("form", f.name)} ?? "")}
            onChange={(e) => setForm({ ...form, ${recordUpdate(f.name, valueCoerce)} })}${f.required ? '\n            required' : ""}${f.placeholder ? `\n            placeholder="${f.placeholder}"` : ""}
          />
        </div>`;
}

function generateFormFromSpec(
  resource: string,
  formSpec: import("./php-analyzer.js").FormSpec,
  isEdit: boolean,
): string {
  const modelName = toPascalCase(resource);
  const pageName = isEdit ? `${modelName}EditPage` : `${modelName}NewPage`;
  const pageTitle = isEdit ? `${modelName} 編集` : `${modelName} 新規作成`;
  const apiUrl = isEdit
    ? `\`/api/${pluralize(resource)}/\${id}\``
    : `"/api/${pluralize(resource)}"`;
  const apiMethod = isEdit ? "PUT" : "POST";
  const hasFile = formSpec.fields.some((f) => f.type === "file");
  const arrayFields = formSpec.fields.filter((f) => f.isArray);
  const hasArrayFields = arrayFields.length > 0;

  const fieldsJsx = formSpec.fields
    .filter((f) => !f.isArray && f.type !== "hidden")
    .map((f, i) => generateFormFieldJsx(f, i))
    .filter(Boolean)
    .join("\n\n");

  // Array fields: generate dynamic slot section
  let arrayFieldsJsx = "";
  if (hasArrayFields) {
    const slotFields = arrayFields
      .map((f) => `              <input
                type="${f.type === "number" ? "number" : f.type === "datetime-local" ? "datetime-local" : "text"}"
                placeholder="${f.label}"
                value={String(${recordAccess("slot", f.name)} ?? "")}
                onChange={(e) => {
                  const updated = [...slots];
                  updated[i] = { ...updated[i]!, ${recordUpdate(f.name, "e.target.value")} };
                  setSlots(updated);
                }}
              />`)
      .join("\n");

    arrayFieldsJsx = `
        <div className="wp-slot-section">
          <div className="wp-slot-header">
            <h3>イベント枠</h3>
            <button
              type="button"
              className="wp-button wp-button-add"
              onClick={() => setSlots([...slots, {}])}
            >
              ＋ 枠追加
            </button>
          </div>
          {slots.map((slot, i) => (
            <div key={i} className="wp-slot-row">
${slotFields}
              <button
                type="button"
                className="wp-button wp-button-danger"
                onClick={() => setSlots(slots.filter((_, j) => j !== i))}
              >
                ✕
              </button>
            </div>
          ))}
        </div>`;
  }

  const paramsLine = isEdit ? `\n  const params = useParams();\n  const id = params.id;` : "";
  const editFetch = isEdit ? `
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    fetch(\`/api/${pluralize(resource)}/\${id}\`)
      .then((res) => res.json())
      .then((data) => { setForm(data); setLoading(false); })
      .catch(() => setLoading(false));
  }, [id]);
` : "";

  return `"use client";

import { useState${isEdit ? ", useEffect" : ""} } from "react";
import { useRouter${isEdit ? ", useParams" : ""} } from "next/navigation";

export default function ${pageName}() {
  const router = useRouter();${paramsLine}
  const [form, setForm] = useState<Record<string, string | number | boolean>>({});${hasArrayFields ? "\n  const [slots, setSlots] = useState<Record<string, string | number>[]>([{}]);" : ""}${hasFile ? "\n  const [file, setFile] = useState<File | null>(null);" : ""}
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);${editFetch}

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    setError(null);

    try {${hasFile ? `
      const formData = new FormData();
      for (const [k, v] of Object.entries(form)) formData.append(k, String(v));
      if (file) formData.append("banner_img", file);
      const res = await fetch(${apiUrl}, { method: "${apiMethod}", body: formData });` : hasArrayFields ? `
      const payload = { ...form, slots };
      const res = await fetch(${apiUrl}, {
        method: "${apiMethod}",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });` : `
      const res = await fetch(${apiUrl}, {
        method: "${apiMethod}",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });`}

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? "保存に失敗しました");
      }

      router.push("/${pluralize(resource)}");
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : "エラーが発生しました");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="wp-admin-wrap">
      <h1 className="wp-admin-title">${pageTitle}</h1>

      {error && (
        <div className="wp-notice wp-notice-error">
          <p>{error}</p>
        </div>
      )}

      <form onSubmit={handleSubmit}>
${fieldsJsx}
${arrayFieldsJsx}
        <div style={{ display: "flex", gap: "12px", marginTop: "24px" }}>
          <button
            type="submit"
            disabled={submitting}
            className="wp-button wp-button-primary"
          >
            {submitting ? "保存中..." : "${formSpec.submitLabel}"}{submitting && <span className="wp-spinner" />}
          </button>
          <button
            type="button"
            onClick={() => router.back()}
            className="wp-button"
          >
            キャンセル
          </button>
        </div>
      </form>
    </div>
  );
}
`;
}

function generateFormPage(
  resource: string,
  table: TableDefinition | undefined,
  analysis: PhpFileAnalysis | undefined,
  isEdit: boolean,
  fw: UiFramework,
): string {
  // If PHP template has a form spec, generate faithful form
  if (analysis?.formSpec && analysis.formSpec.fields.length > 0) {
    return generateFormFromSpec(resource, analysis.formSpec, isEdit);
  }

  const modelName = toPascalCase(table?.name ?? resource);
  const camelModel = toCamelCase(table?.name ?? resource);

  // Determine form fields from PHP analysis input params or table columns
  const formFields: Array<{ name: string; type: string; label: string }> = [];

  if (analysis && analysis.inputParams.length > 0) {
    for (const param of analysis.inputParams) {
      if (param.source === "$_FILES") continue;
      if (param.name === "id" || param.name === "update" || param.name === "delete") continue;
      const col = table?.columns.find((c) => c.name === param.name);
      formFields.push({
        name: param.name.replace(/\[\]$/, ""),
        type: col ? tableInputType(col.type) : "text",
        label: col?.comment ?? fieldLabel(param.name),
      });
    }
  }

  // Fallback: if no fields from analysis params, use table columns
  if (formFields.length === 0 && table) {
    for (const col of table.columns) {
      if (col.isPrimary && col.isAutoIncrement) continue;
      formFields.push({
        name: col.name,
        type: tableInputType(col.type),
        label: col.comment ?? fieldLabel(col.name),
      });
    }
  }

  const pageName = isEdit ? `${modelName}EditPage` : `${modelName}NewPage`;
  const pageTitle = isEdit ? `${modelName} 編集` : `${modelName} 新規作成`;
  const apiMethod = isEdit ? "PUT" : "POST";
  const apiUrl = isEdit
    ? `\`/api/${pluralize(resource)}/\${id}\``
    : `"/api/${pluralize(resource)}"`;

  const editFetch = isEdit
    ? `
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(\`/api/${pluralize(resource)}/\${id}\`)
      .then((res) => res.json())
      .then((data) => {
        setForm(data);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [id]);
`
    : "";

  const paramsLine = isEdit
    ? `\n  const params = useParams();\n  const id = params.id;`
    : "";

  const jsxPreamble = `"use client";

import { useState${isEdit ? ", useEffect" : ""} } from "react";
import { useRouter${isEdit ? ", useParams" : ""} } from "next/navigation";

export default function ${pageName}() {
  const router = useRouter();${paramsLine}
  const [form, setForm] = useState<Record<string, string | number | boolean>>({});
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);${editFetch}

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    setError(null);

    try {
      const res = await fetch(${apiUrl}, {
        method: "${apiMethod}",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? "保存に失敗しました");
      }

      router.push("/${pluralize(resource)}");
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : "エラーが発生しました");
    } finally {
      setSubmitting(false);
    }
  };

`;

  if (fw === "tailwind") {
    return jsxPreamble + `  return (
    <div className="p-6 max-w-3xl">
      <h1 className="text-2xl font-bold mb-6">${pageTitle}</h1>

      {error && (
        <div className="p-3 bg-red-50 text-red-600 rounded-md mb-4">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit}>
        <div className="grid gap-4 max-w-2xl">
${formFields
  .map(
    (f) => `          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium">
              ${f.label}
            </label>
            <input
              type="${f.type}"
              value={String(${recordAccess("form", f.name)} ?? "")}
              onChange={(e) => setForm({ ...form, ${recordUpdate(f.name, f.type === "number" ? "Number(e.target.value)" : f.type === "checkbox" ? "e.target.checked" : "e.target.value")} })}
              className="px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>`,
  )
  .join("\n")}
        </div>

        <div className="flex gap-3 mt-6">
          <button
            type="submit"
            disabled={submitting}
            className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
          >
            {submitting ? "保存中..." : "保存"}
          </button>
          <button
            type="button"
            onClick={() => router.back()}
            className="px-4 py-2 bg-gray-100 text-gray-700 border border-gray-300 rounded-md hover:bg-gray-200"
          >
            キャンセル
          </button>
        </div>
      </form>
    </div>
  );
}
`;
  }

  return jsxPreamble + `  return (
    <div className="wp-admin-wrap">
      <h1 className="wp-admin-title">${pageTitle}</h1>

      {error && (
        <div className="wp-notice wp-notice-error">
          <p>{error}</p>
        </div>
      )}

      <form onSubmit={handleSubmit}>
${formFields
  .map(
    (f) => `        <div className="wp-form-field">
          <label>
            ${f.label}
          </label>
          <input
            className="wp-form-input"
            type="${f.type}"
            value={String(${recordAccess("form", f.name)} ?? "")}
            onChange={(e) => setForm({ ...form, ${recordUpdate(f.name, f.type === "number" ? "Number(e.target.value)" : f.type === "checkbox" ? "e.target.checked" : "e.target.value")} })}
          />
        </div>`,
  )
  .join("\n")}

        <div style={{ display: "flex", gap: "12px", marginTop: "24px" }}>
          <button
            type="submit"
            disabled={submitting}
            className="wp-button wp-button-primary"
          >
            {submitting ? "保存中..." : "保存"}{submitting && <span className="wp-spinner" />}
          </button>
          <button
            type="button"
            onClick={() => router.back()}
            className="wp-button"
          >
            キャンセル
          </button>
        </div>
      </form>
    </div>
  );
}
`;
}

function generateDetailPage(
  resource: string,
  table: TableDefinition | undefined,
  fw: UiFramework,
): string {
  const modelName = toPascalCase(table?.name ?? resource);
  const camelModel = toCamelCase(table?.name ?? resource);
  const columns = table?.columns ?? [];

  if (fw === "tailwind") {
    return `import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function ${modelName}SummaryPage() {
  const items = await prisma.${camelModel}.findMany({
    orderBy: { id: "desc" },
    take: 50,
  });

  const total = await prisma.${camelModel}.count();

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-6">${modelName} サマリー</h1>

      <div className="mb-6 p-4 bg-blue-50 rounded-lg">
        <p className="text-sm text-gray-500">総件数</p>
        <p className="text-3xl font-bold text-blue-800">{total}</p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="bg-gray-100">
${columns.slice(0, 6).map((c) => `              <th className="px-4 py-3 text-left border-b-2 border-gray-200 text-sm">${jsxText(c.comment ?? fieldLabel(c.name))}</th>`).join("\n")}
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.id} className="border-b border-gray-200">
${columns.slice(0, 6).map((c) => `                <td className="px-4 py-3 text-sm">{String(${recordAccess("item", c.name)} ?? "")}</td>`).join("\n")}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
`;
  }

  return `import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function ${modelName}SummaryPage() {
  const items = await prisma.${camelModel}.findMany({
    orderBy: { id: "desc" },
    take: 50,
  });

  const total = await prisma.${camelModel}.count();

  return (
    <div className="wp-admin-wrap">
      <h1 className="wp-admin-title">${modelName} サマリー</h1>

      <div className="wp-dashboard-card" style={{ marginBottom: "24px", display: "inline-block" }}>
        <div className="wp-dashboard-card-header">総件数</div>
        <div className="wp-dashboard-card-body">
          <span className="wp-dashboard-card-count">{total}</span>
        </div>
      </div>

      <table className="wp-list-table">
        <thead>
          <tr>
${columns.slice(0, 6).map((c) => `            <th>${jsxText(c.comment ?? fieldLabel(c.name))}</th>`).join("\n")}
          </tr>
        </thead>
        <tbody>
          {items.map((item) => (
            <tr key={item.id}>
${columns.slice(0, 6).map((c) => `              <td>{String(${recordAccess("item", c.name)} ?? "")}</td>`).join("\n")}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
`;
}

function generateDashboardPage(tables: TableDefinition[], fw: UiFramework): string {
  const countQueries = tables
    .map(
      (t) =>
        `    prisma.${toCamelCase(t.name)}.count(),`,
    )
    .join("\n");

  const destructuring = tables.map((t, i) => `count${i}`).join(", ");

  if (fw === "tailwind") {
    const twCards = tables
      .map(
        (t, i) => `        <a key="${t.name}" href="/${pluralize(t.name)}" className="block p-6 bg-white rounded-lg shadow-sm no-underline text-inherit">
          <p className="text-sm text-gray-500">${toPascalCase(t.name)}</p>
          <p className="text-3xl font-bold text-blue-800">{count${i}}</p>
        </a>`,
      )
      .join("\n");

    return `import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function DashboardPage() {
  const [${destructuring}] = await Promise.all([
${countQueries}
  ]);

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-6">ダッシュボード</h1>

      <div className="grid grid-cols-[repeat(auto-fill,minmax(200px,1fr))] gap-4">
${twCards}
      </div>
    </div>
  );
}
`;
  }

  const cards = tables
    .map(
      (t, i) => `        <a key="${t.name}" href="/${pluralize(t.name)}" className="wp-dashboard-card">
          <div className="wp-dashboard-card-header">${toPascalCase(t.name)}</div>
          <div className="wp-dashboard-card-body">
            <span className="wp-dashboard-card-count">{count${i}}</span>
          </div>
        </a>`,
    )
    .join("\n");

  return `import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function DashboardPage() {
  const [${destructuring}] = await Promise.all([
${countQueries}
  ]);

  return (
    <div className="wp-admin-wrap">
      <h1 className="wp-admin-title">ダッシュボード</h1>

      <div className="wp-dashboard-grid">
${cards}
      </div>
    </div>
  );
}
`;
}

function generateAdminLayout(
  pages: AdminPage[],
  tables: TableDefinition[],
  fw: UiFramework,
  requireAuth: boolean,
): string {
  // Derive menu items from list pages
  const menuItems: Array<{ label: string; href: string }> = [];

  // Dashboard
  menuItems.push({ label: "ダッシュボード", href: "/" });

  // Collect unique resource list pages
  const seen = new Set<string>();
  for (const page of pages) {
    if (page.type !== "list") continue;
    // Extract resource path from page path: app/(admin)/articles/page.tsx -> /articles
    const match = page.path.match(/app\/\(admin\)\/([^/]+)\/page\.tsx$/);
    if (match && !seen.has(match[1]!)) {
      seen.add(match[1]!);
      const resource = match[1]!;
      menuItems.push({
        label: toPascalCase(resource) + " 一覧",
        href: `/${resource}`,
      });
    }
  }

  // Add nav links for tables not already covered by list pages
  for (const t of tables) {
    if (!seen.has(t.name) && !seen.has(pluralize(t.name))) {
      seen.add(t.name);
      menuItems.push({
        label: toPascalCase(t.name),
        href: `/${t.name}`,
      });
    }
  }

  const authImports = requireAuth
    ? 'import { redirect } from "next/navigation";\nimport { requireActiveAccess } from "@/lib/require-active-user";\n'
    : "";
  const layoutDeclaration = requireAuth
    ? "export default async function AdminLayout"
    : "export default function AdminLayout";
  const authCheck = requireAuth
    ? `  if (!(await requireActiveAccess("/"))) {
    redirect("/unauthorized");
  }

`
    : "";

  if (fw === "tailwind") {
    const twMenuItems = menuItems
      .map(
        (item) => `            <a
              href="${item.href}"
              className="block px-4 py-2.5 text-gray-300 rounded-md text-sm hover:bg-gray-700 hover:text-white"
            >
              ${item.label}
            </a>`,
      )
      .join("\n");

    return `import type { ReactNode } from "react";
${authImports}

${layoutDeclaration}({ children }: { children: ReactNode }) {
${authCheck}  return (
    <div className="flex min-h-screen">
      {/* Sidebar */}
      <nav className="w-60 bg-gray-800 text-white py-6 shrink-0">
        <div className="px-4 mb-8">
          <h2 className="text-lg font-bold">管理画面</h2>
        </div>
        <div className="flex flex-col gap-1">
${twMenuItems}
        </div>
      </nav>

      {/* Main content */}
      <main className="flex-1 bg-gray-50 overflow-auto">
        {children}
      </main>
    </div>
  );
}
`;
  }

  const menuItemsJsx = menuItems
    .map(
      (item) => `            <a href="${item.href}" className="wp-admin-menu-item">
              ${item.label}
            </a>`,
    )
    .join("\n");

  return `import type { ReactNode } from "react";
import "@/app/globals.css";
${authImports}

${layoutDeclaration}({ children }: { children: ReactNode }) {
${authCheck}  return (
    <div style={{ display: "flex", minHeight: "100vh" }}>
      {/* Sidebar */}
      <nav className="wp-admin-sidebar">
        <h2>管理画面</h2>
        <div style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
${menuItemsJsx}
        </div>
      </nav>

      {/* Main content */}
      <main className="wp-admin-content">
        {children}
      </main>
    </div>
  );
}
`;
}

// ── Table-driven helpers ──

function getPrimaryKey(table: TableDefinition): { name: string; type: string } {
  const pk = table.columns.find((c) => c.isPrimary);
  if (pk) return { name: pk.name, type: pk.type };
  // Fallback: column named "id", or first column
  const idCol = table.columns.find((c) => c.name === "id");
  if (idCol) return { name: idCol.name, type: idCol.type };
  const first = table.columns[0];
  return first ? { name: first.name, type: first.type } : { name: "id", type: "Int" };
}

function pkCoerce(pkType: string, expr: string): string {
  if (pkType === "BigInt") return `BigInt(${expr})`;
  return pkType === "Int" || pkType === "Float"
    ? `Number(${expr})`
    : expr;
}

function tableInputType(columnType: string): string {
  // BigInt values arrive from JSON as decimal strings. Keep them strings in
  // client forms and URLs so values above Number.MAX_SAFE_INTEGER are exact.
  return columnType === "BigInt" ? "text" : fieldTypeToInputType(columnType);
}

// ── Table-driven CRUD page generators ──

function generateTableListPage(
  table: TableDefinition,
  fw: UiFramework,
  hasSinglePk = true,
): AdminPage {
  const modelName = toPascalCase(table.name);
  const camelModel = toCamelCase(table.name);
  const pk = getPrimaryKey(table);
  const columns = table.columns.slice(0, 6);

  let content: string;
  if (fw === "tailwind") {
    content = `import { prisma } from "@/lib/db";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default async function ${modelName}ListPage() {
  const items = await prisma.${camelModel}.findMany({
    orderBy: { ${codeKey(pk.name)}: "desc" },
    take: 100,
  });

  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">${modelName} 一覧</h1>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="bg-gray-100">
${columns.map((c) => `              <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">${jsxText(c.comment ?? c.name)}</th>`).join("\n")}
              <th className="px-4 py-3"></th>
            </tr>
          </thead>
          <tbody>
            {items.map((item: Record<string, unknown>) => (
              <tr key={String(${recordAccess("item", pk.name)})} className="border-t border-gray-200">
${columns.map((c) => `                <td className="px-4 py-3 text-sm">{String(${recordAccess("item", c.name)} ?? "")}</td>`).join("\n")}
                ${hasSinglePk ? `<td className="px-4 py-3">
                  <Link href={\`/${pluralize(table.name)}/\${String(${recordAccess("item", pk.name)})}\`} className="text-blue-600 underline mr-2">
                    詳細
                  </Link>
                  <Link href={\`/${pluralize(table.name)}/\${String(${recordAccess("item", pk.name)})}/edit\`} className="text-blue-600 underline">
                    編集
                  </Link>
                </td>` : `<td className="px-4 py-3 text-xs text-gray-400">{/* composite-key table — no single-record routes */}</td>`}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {items.length === 0 && (
        <p className="text-center py-12 text-gray-500">
          データがありません
        </p>
      )}
    </div>
  );
}
`;
  } else {
    content = `import { prisma } from "@/lib/db";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default async function ${modelName}ListPage() {
  const items = await prisma.${camelModel}.findMany({
    orderBy: { ${codeKey(pk.name)}: "desc" },
    take: 100,
  });

  return (
    <div className="wp-admin-wrap">
      <div className="wp-admin-header">
        <h1 className="wp-admin-title">${modelName} 一覧</h1>
      </div>
      <div className="wp-table-nav">
        <span className="displaying-num">{items.length} 件</span>
      </div>
      <table className="wp-list-table">
        <thead>
          <tr>
${columns.map((c) => `            <th>${jsxText(c.comment ?? c.name)}</th>`).join("\n")}
            <th></th>
          </tr>
        </thead>
        <tbody>
          {items.map((item: Record<string, unknown>) => (
            <tr key={String(${recordAccess("item", pk.name)})}>
${columns.map((c) => `              <td>{String(${recordAccess("item", c.name)} ?? "")}</td>`).join("\n")}
              ${hasSinglePk ? `<td className="wp-row-action">
                <Link href={\`/${pluralize(table.name)}/\${String(${recordAccess("item", pk.name)})}\`} className="wp-row-action">
                  詳細
                </Link>
                {" / "}
                <Link href={\`/${pluralize(table.name)}/\${String(${recordAccess("item", pk.name)})}/edit\`} className="wp-row-action">
                  編集
                </Link>
              </td>` : `<td className="wp-row-action">{/* composite-key table — no single-record routes */}</td>`}
            </tr>
          ))}
        </tbody>
      </table>
      {items.length === 0 && (
        <p className="wp-empty-state">
          データがありません
        </p>
      )}
    </div>
  );
}
`;
  }

  return {
    path: `app/(admin)/${pluralize(table.name)}/page.tsx`,
    content,
    type: "list" as const,
  };
}

function generateTableDetailPage(
  table: TableDefinition,
  fw: UiFramework,
): AdminPage {
  const modelName = toPascalCase(table.name);
  const camelModel = toCamelCase(table.name);
  const pk = getPrimaryKey(table);
  const columns = table.columns;

  let content: string;
  if (fw === "tailwind") {
    content = `import { prisma } from "@/lib/db";
import Link from "next/link";
import { notFound } from "next/navigation";

export const dynamic = "force-dynamic";

export default async function ${modelName}DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = await prisma.${camelModel}.findUnique({ where: { ${codeKey(pk.name)}: ${pkCoerce(pk.type, "id")} } });
  if (!item) return notFound();

  async function handleDelete() {
    "use server";
    await fetch(\`\${process.env.NEXT_PUBLIC_BASE_URL ?? ""}/api/${pluralize(table.name)}/\${id}\`, { method: "DELETE" });
  }

  return (
    <div className="p-6 max-w-3xl">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">${modelName} 詳細</h1>
        <div className="flex gap-2">
          <Link href={\`/${pluralize(table.name)}/\${id}/edit\`} className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">
            編集
          </Link>
          <form action={handleDelete}>
            <button type="submit" className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700">
              DELETE
            </button>
          </form>
        </div>
      </div>

      <dl className="grid grid-cols-[max-content_1fr] gap-x-6 gap-y-3">
${columns.map((c) => `        <dt className="text-sm font-medium text-gray-500">${jsxText(c.comment ?? c.name)}</dt>
        <dd className="text-sm">{String(${recordAccess("(item as Record<string, unknown>)", c.name)} ?? "")}</dd>`).join("\n")}
      </dl>
    </div>
  );
}
`;
  } else {
    content = `import { prisma } from "@/lib/db";
import Link from "next/link";
import { notFound } from "next/navigation";

export const dynamic = "force-dynamic";

export default async function ${modelName}DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = await prisma.${camelModel}.findUnique({ where: { ${codeKey(pk.name)}: ${pkCoerce(pk.type, "id")} } });
  if (!item) return notFound();

  async function handleDelete() {
    "use server";
    await fetch(\`\${process.env.NEXT_PUBLIC_BASE_URL ?? ""}/api/${pluralize(table.name)}/\${id}\`, { method: "DELETE" });
  }

  return (
    <div className="wp-admin-wrap">
      <div className="wp-admin-header">
        <h1 className="wp-admin-title">${modelName} 詳細</h1>
        <div style={{ display: "flex", gap: "8px" }}>
          <Link href={\`/${pluralize(table.name)}/\${id}/edit\`} className="wp-button wp-button-primary">
            編集
          </Link>
          <form action={handleDelete}>
            <button type="submit" className="wp-button wp-button-danger">
              DELETE
            </button>
          </form>
        </div>
      </div>

      <dl style={{ display: "grid", gridTemplateColumns: "max-content 1fr", columnGap: "24px", rowGap: "12px" }}>
${columns.map((c) => `        <dt style={{ fontSize: "14px", fontWeight: "500", color: "#6b7280" }}>${jsxText(c.comment ?? c.name)}</dt>
        <dd style={{ fontSize: "14px" }}>{String(${recordAccess("(item as Record<string, unknown>)", c.name)} ?? "")}</dd>`).join("\n")}
      </dl>
    </div>
  );
}
`;
  }

  return {
    path: `app/(admin)/${pluralize(table.name)}/[id]/page.tsx`,
    content,
    type: "detail" as const,
  };
}

function generateTableFormPage(
  table: TableDefinition,
  isEdit: boolean,
  fw: UiFramework,
): AdminPage {
  const modelName = toPascalCase(table.name);
  const camelModel = toCamelCase(table.name);

  const formFields: Array<{ name: string; type: string; label: string }> = [];
  for (const col of table.columns) {
    if (col.isPrimary && col.isAutoIncrement) continue;
    formFields.push({
      name: col.name,
      type: tableInputType(col.type),
      label: col.comment ?? fieldLabel(col.name),
    });
  }

  const pageName = isEdit ? `${modelName}EditPage` : `${modelName}NewPage`;
  const pageTitle = isEdit ? `${modelName} 編集` : `${modelName} 新規作成`;
  const apiMethod = isEdit ? "PUT" : "POST";
  const apiResource = pluralize(table.name);
  const apiUrl = isEdit
    ? `\`/api/${apiResource}/\${id}\``
    : `"/api/${apiResource}"`;

  const editFetch = isEdit
    ? `
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(\`/api/${pluralize(table.name)}/\${id}\`)
      .then((res) => res.json())
      .then((data) => {
        setForm(data);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [id]);
`
    : "";

  const paramsLine = isEdit
    ? `\n  const params = useParams();\n  const id = params.id;`
    : "";

  const redirectPath = `/${pluralize(table.name)}`;

  const jsxPreamble = `"use client";

import { useState${isEdit ? ", useEffect" : ""} } from "react";
import { useRouter${isEdit ? ", useParams" : ""} } from "next/navigation";

export default function ${pageName}() {
  const router = useRouter();${paramsLine}
  const [form, setForm] = useState<Record<string, string | number | boolean>>({});
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);${editFetch}

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    setError(null);

    try {
      const res = await fetch(${apiUrl}, {
        method: "${apiMethod}",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? "保存に失敗しました");
      }

      router.push("${redirectPath}");
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : "エラーが発生しました");
    } finally {
      setSubmitting(false);
    }
  };

`;

  let content: string;
  if (fw === "tailwind") {
    content = jsxPreamble + `  return (
    <div className="p-6 max-w-3xl">
      <h1 className="text-2xl font-bold mb-6">${pageTitle}</h1>

      {error && (
        <div className="p-3 bg-red-50 text-red-600 rounded-md mb-4">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit}>
        <div className="grid gap-4 max-w-2xl">
${formFields
  .map(
    (f) => `          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium">
              ${f.label}
            </label>
            <input
              type="${f.type}"
              value={String(${recordAccess("form", f.name)} ?? "")}
              onChange={(e) => setForm({ ...form, ${recordUpdate(f.name, f.type === "number" ? "Number(e.target.value)" : f.type === "checkbox" ? "e.target.checked" : "e.target.value")} })}
              className="px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>`,
  )
  .join("\n")}
        </div>

        <div className="flex gap-3 mt-6">
          <button
            type="submit"
            disabled={submitting}
            className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
          >
            {submitting ? "保存中..." : "保存"}
          </button>
          <button
            type="button"
            onClick={() => router.back()}
            className="px-4 py-2 bg-gray-100 text-gray-700 border border-gray-300 rounded-md hover:bg-gray-200"
          >
            キャンセル
          </button>
        </div>
      </form>
    </div>
  );
}
`;
  } else {
    content = jsxPreamble + `  return (
    <div className="wp-admin-wrap">
      <h1 className="wp-admin-title">${pageTitle}</h1>

      {error && (
        <div className="wp-notice wp-notice-error">
          <p>{error}</p>
        </div>
      )}

      <form onSubmit={handleSubmit}>
${formFields
  .map(
    (f) => `        <div className="wp-form-field">
          <label>
            ${f.label}
          </label>
          <input
            className="wp-form-input"
            type="${f.type}"
            value={String(${recordAccess("form", f.name)} ?? "")}
            onChange={(e) => setForm({ ...form, ${recordUpdate(f.name, f.type === "number" ? "Number(e.target.value)" : f.type === "checkbox" ? "e.target.checked" : "e.target.value")} })}
          />
        </div>`,
  )
  .join("\n")}

        <div style={{ display: "flex", gap: "12px", marginTop: "24px" }}>
          <button
            type="submit"
            disabled={submitting}
            className="wp-button wp-button-primary"
          >
            {submitting ? "保存中..." : "保存"}{submitting && <span className="wp-spinner" />}
          </button>
          <button
            type="button"
            onClick={() => router.back()}
            className="wp-button"
          >
            キャンセル
          </button>
        </div>
      </form>
    </div>
  );
}
`;
  }

  // Use pluralized path to match list page (generateTableListPage uses pluralize)
  const resource = pluralize(table.name);
  const path = isEdit
    ? `app/(admin)/${resource}/[id]/edit/page.tsx`
    : `app/(admin)/${resource}/new/page.tsx`;

  return {
    path,
    content,
    type: "form" as const,
  };
}

// ── Public API ──

export function generateAdminScaffold(
  analyses: PhpFileAnalysis[],
  tables: TableDefinition[],
  options?: AdminScaffoldOptions,
): AdminPage[] {
  const fw: UiFramework = options?.uiFramework ?? "plain";
  const pages: AdminPage[] = [];
  const processedPaths = new Set<string>();

  // Group analyses by resource for finding related form analysis
  const analysisByFile = new Map<string, PhpFileAnalysis>();
  for (const a of analyses) {
    analysisByFile.set(a.fileName, a);
  }

  // Process each PHP template file
  for (const analysis of analyses) {
    const mapping = mapPhpToRoute(analysis.fileName);
    if (!mapping) continue;
    if (processedPaths.has(mapping.path)) continue;

    processedPaths.add(mapping.path);
    const table = findTableForResource(mapping.resource, tables);

    let content: string;
    switch (mapping.type) {
      case "list":
        content = generateListPage(mapping.resource, table, analyses, fw);
        break;
      case "form": {
        const isEdit = mapping.path.includes("[id]") && !mapping.path.includes("copy");
        content = generateFormPage(mapping.resource, table, analysis, isEdit, fw);
        break;
      }
      case "detail":
        content = generateDetailPage(mapping.resource, table, fw);
        break;
      default:
        continue;
    }

    pages.push({ path: mapping.path, content, type: mapping.type });
  }

  // Add table-driven CRUD pages — fill gaps for all tables
  if (tables.length > 0) {
    const existingPaths = new Set(pages.map((p) => p.path));

    // Helper: check if path exists in singular or plural form
    const hasPath = (pattern: string) => {
      return existingPaths.has(pattern);
    };

    for (const table of tables) {
      const s = table.name;           // singular (table name)
      const p = pluralize(s);         // plural
      const pre = "app/(admin)/";

      // Composite-key tables (no single isPrimary and no "id" column) cannot
      // use findUnique({ where: { id } }) — skip detail/edit/new and keep
      // only the list page for operational visibility.
      const hasSinglePk =
        table.columns.some(c => c.isPrimary) ||
        table.columns.some(c => c.name === "id");

      // List page
      if (!hasPath(`${pre}${s}/page.tsx`) && !hasPath(`${pre}${p}/page.tsx`)) {
        pages.push(generateTableListPage(table, fw, hasSinglePk));
        existingPaths.add(`${pre}${s}/page.tsx`);
      }

      if (!hasSinglePk) continue;

      // Detail page (singular only — PHP form pages at plural/[id] are NOT detail)
      if (!hasPath(`${pre}${s}/[id]/page.tsx`)) {
        pages.push(generateTableDetailPage(table, fw));
        existingPaths.add(`${pre}${s}/[id]/page.tsx`);
      }

      // Edit page
      if (!hasPath(`${pre}${s}/[id]/edit/page.tsx`) && !hasPath(`${pre}${p}/[id]/edit/page.tsx`)) {
        pages.push(generateTableFormPage(table, true, fw));
        existingPaths.add(`${pre}${s}/[id]/edit/page.tsx`);
      }

      // New page
      if (!hasPath(`${pre}${s}/new/page.tsx`) && !hasPath(`${pre}${p}/new/page.tsx`)) {
        pages.push(generateTableFormPage(table, false, fw));
        existingPaths.add(`${pre}${s}/new/page.tsx`);
      }
    }
  }

  // Generate globals.css
  pages.push({
    path: "app/globals.css",
    content: generateGlobalsCss(),
    type: "dashboard" as const,
  });

  // Generate admin layout
  pages.push({
    path: "app/(admin)/layout.tsx",
    content: generateAdminLayout(pages, tables, fw, options?.requireAuth ?? false),
    type: "dashboard",
  });

  // Generate dashboard page
  pages.push({
    path: "app/(admin)/page.tsx",
    content: generateDashboardPage(tables, fw),
    type: "dashboard",
  });

  return pages;
}
