/**
 * Migration Quality Dashboard Generator
 *
 * Generates a standalone HTML report summarizing migration quality metrics:
 * file counts, CRUD coverage, security issues, and TODO items.
 */

// ── Types ──

export interface DashboardInput {
  projectName: string;
  phpFileCount: number;
  tableCount: number;
  apiRouteCount: number;
  adminPageCount: number;
  authGenerated: boolean;
  securityIssues: Array<{ file: string; issue: string }>;
  crudCoverage: Array<{
    table: string;
    create: boolean;
    read: boolean;
    update: boolean;
    delete: boolean;
  }>;
  generatedFiles: number;
}

export interface DashboardOutput {
  html: string;
  path: string;
}

// ── Generator ──

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function generateMigrationDashboard(
  input: DashboardInput,
): DashboardOutput {
  const crudRows = input.crudCoverage
    .map((c) => {
      const check = (v: boolean) =>
        v
          ? '<span style="color:#22c55e">&#10003;</span>'
          : '<span style="color:#ef4444">&#10007;</span>';
      return `<tr><td>${escapeHtml(c.table)}</td><td>${check(c.create)}</td><td>${check(c.read)}</td><td>${check(c.update)}</td><td>${check(c.delete)}</td></tr>`;
    })
    .join("\n");

  const securityRows =
    input.securityIssues.length > 0
      ? input.securityIssues
          .map(
            (s) =>
              `<tr><td>${escapeHtml(s.file)}</td><td>${escapeHtml(s.issue)}</td></tr>`,
          )
          .join("\n")
      : '<tr><td colspan="2" style="text-align:center;color:#22c55e">No security issues detected</td></tr>';

  const crudTotal = input.crudCoverage.length;
  const crudFull = input.crudCoverage.filter(
    (c) => c.create && c.read && c.update && c.delete,
  ).length;
  const crudPercent =
    crudTotal > 0 ? Math.round((crudFull / crudTotal) * 100) : 0;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Migration Report: ${escapeHtml(input.projectName)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }
    h1 { font-size: 1.5rem; margin-bottom: 1.5rem; color: #38bdf8; }
    h2 { font-size: 1.1rem; margin: 1.5rem 0 0.75rem; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
    .card { background: #1e293b; border-radius: 0.5rem; padding: 1.25rem; text-align: center; }
    .card .value { font-size: 2rem; font-weight: 700; color: #38bdf8; }
    .card .label { font-size: 0.75rem; color: #94a3b8; margin-top: 0.25rem; }
    table { width: 100%; border-collapse: collapse; background: #1e293b; border-radius: 0.5rem; overflow: hidden; }
    th { background: #334155; padding: 0.5rem 1rem; text-align: left; font-size: 0.75rem; text-transform: uppercase; color: #94a3b8; }
    td { padding: 0.5rem 1rem; border-top: 1px solid #334155; font-size: 0.875rem; }
    .footer { margin-top: 2rem; font-size: 0.75rem; color: #64748b; text-align: center; }
  </style>
</head>
<body>
  <h1>Migration Report: ${escapeHtml(input.projectName)}</h1>

  <div class="grid">
    <div class="card"><div class="value">${input.phpFileCount}</div><div class="label">PHP Files</div></div>
    <div class="card"><div class="value">${input.tableCount}</div><div class="label">DB Tables</div></div>
    <div class="card"><div class="value">${input.apiRouteCount}</div><div class="label">API Routes</div></div>
    <div class="card"><div class="value">${input.adminPageCount}</div><div class="label">Admin Pages</div></div>
    <div class="card"><div class="value">${input.generatedFiles}</div><div class="label">Generated Files</div></div>
    <div class="card"><div class="value">${crudPercent}%</div><div class="label">CRUD Coverage</div></div>
  </div>

  <h2>CRUD Coverage</h2>
  <table>
    <thead><tr><th>Table</th><th>Create</th><th>Read</th><th>Update</th><th>Delete</th></tr></thead>
    <tbody>${crudRows}</tbody>
  </table>

  <h2>Security Issues (${input.securityIssues.length})</h2>
  <table>
    <thead><tr><th>File</th><th>Issue</th></tr></thead>
    <tbody>${securityRows}</tbody>
  </table>

  <div class="footer">
    Generated by wp-transfer | ${new Date().toISOString().split("T")[0]}
  </div>
</body>
</html>`;

  return { html, path: "report.html" };
}
