import type { WpSite } from "@wp-transfer/core";

export function generateMultisitePrismaSchema(_sites: WpSite[]): string {
  return `// Multisite Prisma Schema — auto-generated by wp-transfer
// Shared DB with siteId column for tenant isolation

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Site {
  id          Int             @id @default(autoincrement())
  slug        String          @unique
  title       String
  domain      String?
  path        String          @default("/")
  posts       Post[]
  media       Media[]
  userRoles   UserSiteRole[]
}

model Post {
  id          Int      @id @default(autoincrement())
  siteId      Int
  site        Site     @relation(fields: [siteId], references: [id])
  title       String
  slug        String
  content     String   @db.Text
  excerpt     String   @db.Text
  status      String   @default("publish")
  type        String   @default("post")
  authorId    Int?
  author      User?    @relation(fields: [authorId], references: [id])
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  @@index([siteId, slug])
  @@index([siteId, type])
}

model User {
  id          Int             @id @default(autoincrement())
  email       String          @unique
  name        String
  login       String?
  posts       Post[]
  siteRoles   UserSiteRole[]
}

model UserSiteRole {
  id          Int      @id @default(autoincrement())
  userId      Int
  user        User     @relation(fields: [userId], references: [id])
  siteId      Int
  site        Site     @relation(fields: [siteId], references: [id])
  role        String   @default("contributor")
  @@unique([userId, siteId])
}

model Media {
  id          Int      @id @default(autoincrement())
  siteId      Int
  site        Site     @relation(fields: [siteId], references: [id])
  url         String
  title       String?
  alt         String?
  mimeType    String?
  @@index([siteId])
}
`;
}
