import type { WooProduct } from "@wp-transfer/core";

/**
 * Generates a complete Prisma schema string for WooCommerce products.
 *
 * The schema is a static template — model definitions are always the same.
 * The product data only affects the informational comment at the top.
 */
export function generateWooPrismaSchema(products: WooProduct[]): string {
  const totalVariations = products.reduce(
    (sum, p) => sum + p.variations.length,
    0,
  );

  return `// WooCommerce Prisma Schema — generated by wp-transfer
// ${products.length} products, ${totalVariations} variations

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Product {
  id               Int                     @id @default(autoincrement())
  name             String
  slug             String                  @unique
  type             String                  @default("simple")
  status           String                  @default("publish")
  description      String                  @db.Text
  shortDescription String                  @db.Text
  productUrl       String?
  buttonText       String?
  sku              String?
  price            Decimal?                @db.Decimal(10, 2)
  regularPrice     Decimal?                @db.Decimal(10, 2)
  salePrice        Decimal?                @db.Decimal(10, 2)
  stockStatus      String                  @default("instock")
  weight           String?
  createdAt        DateTime                @default(now())
  updatedAt        DateTime                @updatedAt
  variations       ProductVariation[]
  attributes       ProductAttributeValue[]
  categories       ProductCategory[]       @relation("ProductCategories")
  images           ProductImage[]
}

model ProductVariation {
  id           Int      @id @default(autoincrement())
  productId    Int
  product      Product  @relation(fields: [productId], references: [id])
  sku          String?
  price        Decimal? @db.Decimal(10, 2)
  regularPrice Decimal? @db.Decimal(10, 2)
  salePrice    Decimal? @db.Decimal(10, 2)
  stockStatus  String   @default("instock")
  attributes   Json
  createdAt    DateTime @default(now())
}

model ProductAttribute {
  id     Int                    @id @default(autoincrement())
  name   String
  slug   String                 @unique
  values ProductAttributeValue[]
}

model ProductAttributeValue {
  id          Int              @id @default(autoincrement())
  attributeId Int
  attribute   ProductAttribute @relation(fields: [attributeId], references: [id])
  productId   Int
  product     Product          @relation(fields: [productId], references: [id])
  value       String
  isVariation Boolean          @default(false)
}

model ProductCategory {
  id       Int               @id @default(autoincrement())
  name     String
  slug     String            @unique
  parentId Int?
  parent   ProductCategory?  @relation("CategoryTree", fields: [parentId], references: [id])
  children ProductCategory[] @relation("CategoryTree")
  products Product[]         @relation("ProductCategories")
}

model ProductImage {
  id        Int     @id @default(autoincrement())
  productId Int
  product   Product @relation(fields: [productId], references: [id])
  url       String
  alt       String?
  position  Int     @default(0)
}
`;
}
