/**
 * Generates Prisma schema models for WooCommerce orders and customers.
 *
 * These models supplement the existing Product models from C-1.
 * The output is a static template -- no runtime data needed.
 */
export function generateWooOrderPrismaSchema(): string {
  return `// WooCommerce Order/Customer Prisma Schema — generated by wp-transfer
// Supplement to Product models (see woo-prisma-generator)

model Customer {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  firstName String
  lastName  String
  orders    Order[]
}

model Order {
  id         Int         @id @default(autoincrement())
  status     String
  total      Decimal     @db.Decimal(10, 2)
  currency   String      @default("USD")
  customerId Int
  customer   Customer    @relation(fields: [customerId], references: [id])
  items      OrderItem[]
  createdAt  DateTime    @default(now())
}

model OrderItem {
  id        Int     @id @default(autoincrement())
  orderId   Int
  order     Order   @relation(fields: [orderId], references: [id])
  productId Int?
  name      String
  quantity  Int
  total     Decimal @db.Decimal(10, 2)
}
`;
}
